HomeSchoolLog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('logger/', include('logger.urls', namespace='logger')),  
]

base/urls.py
from django.urls import path
from .views import (
    CustomLoginView, 
    CustomLogoutView, 
    SignUpView, 
    HomeView,
    CreateProfileView,
    ProfileView
)

app_name = 'base'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('create_profile/', CreateProfileView.as_view(), name ='create_profile'),
    path('profile/', ProfileView.as_view(), name='profile')
]

logger/urls.py
from . import views
from django.urls import path


app_name = 'logger'

urlpatterns = [
  path('', views.LogsView.as_view(), name='logs'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    GRADE_CHOICES = [
        ('Kindergarten', 'Kindergarten'),
        ('First', 'First'),
        ('Second', 'Second'),
        ('Third', 'Third'),
        ('Fourth', 'Fourth'),
        ('Fifth', 'Fifth'),
        ('Sixth', 'Sixth'),
        ('Seventh', 'Seventh'),
        ('Eigth', 'Eigth'),
        ('Ninth', 'Ninth'),
        ('Tenth', 'Tenth'),
        ('Eleventh', 'Eleventh'),
        ('Twelfth', 'Twelfth')
    ]

    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    birthdate = models.DateField(blank=False, null=False)
    grade = models.CharField(max_length=255, choices=GRADE_CHOICES, blank=False, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="students")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class StateRequirements(models.Model):
    state = models.CharField(max_length=50, blank=False, null=True)
    core_hours = models.DecimalField(decimal_places=0, max_digits=10)
    total_hours = models.DecimalField(decimal_places=0, max_digits=10)
    year_start = models.DateField()
    year_end = models.DateField()

    def __str__(self):
        return self.state
    
class Profile(models.Model):
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    state = models.ForeignKey(StateRequirements, on_delete=models.CASCADE, related_name='profiles')
    email = models.EmailField()

    def __str__(self):
        return self.user.username
    

base/forms.py
from django import forms
from .models import Profile, Student

class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'first_name', 'last_name', 'state', 'email'

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'first_name', 'last_name', 'state', 'email'

class AddStudentForm(forms.ModelForm):
    birthdate = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
            'format': '%Y-%m-%d'  # Enforcing YYYY-MM-DD format
        })
    )

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'birthdate', 'grade']

class UpdateStudentForm(forms.ModelForm):
    birthdate = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
            'format': '%Y-%m-%d'  # Enforcing YYYY-MM-DD format
        })
    )

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'birthdate', 'grade']

base/views.py
from .forms import CreateProfileForm, UpdateProfileForm, AddStudentForm
from .models import Profile, Student
from .service import DashboardService
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView



from logger.models import Log


class HomeView(LoginRequiredMixin, TemplateView):
    profile_model = Profile
    template_name = 'home.html'
    login_url = '/login'  

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        
        try:
            if not hasattr(self, 'profile_objects'):
                self.profile_objects = Profile.objects.get(user=request.user)

        except Profile.DoesNotExist:
            return redirect('base:create_profile')
        
        if not hasattr(self, 'dashboard_data'):
            self.dashboard_data = DashboardService(request).get_dashboard_data()

        return super(HomeView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs, ):
        context = super().get_context_data(**kwargs)
        context['profile_info'] = self.profile_model.objects.get(user=self.request.user)
        context['dashboard_data'] = self.dashboard_data

        
        return context
    
class CustomLoginView(auth_views.LoginView):
    template_name = 'login.html'

class CustomLogoutView(auth_views.LogoutView):
    template_name = 'logged_out.html'

class SignUpView(FormView):
    template_name = 'signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('base:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class CreateProfileView(LoginRequiredMixin, CreateView):
    model = Profile
    form_class = CreateProfileForm
    template_name = 'create_profile.html'
    success_url = reverse_lazy('base:home')  

    def dispatch(self, request, *args, **kwargs):
        if self.model.objects.filter(user=request.user).exists():
            return redirect('base:home')  
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = request.user
            self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class ProfileView(LoginRequiredMixin, FormView):
    profile_model = Profile
    student_model = Student
    template_name = 'profile.html'
    form_class = UpdateProfileForm
    success_url = reverse_lazy('base:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_info'] = get_object_or_404(self.profile_model, user=self.request.user)
        context['student_info'] = self.student_model.objects.filter(user=self.request.user)
        context['add_student_form'] = AddStudentForm()
        context['edit_student_form'] = AddStudentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if 'edit_profile' in request.POST:
            if form.is_valid():
                instance = self.profile_model.objects.get(user=self.request.user)
                instance.first_name = form.cleaned_data['first_name']
                instance.last_name = form.cleaned_data['last_name']
                instance.state = form.cleaned_data['state']
                instance.email = form.cleaned_data['email']
                instance.save()
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

        if 'add_student' in request.POST:
            add_student_form = AddStudentForm(request.POST)
            if add_student_form.is_valid():
                student = self.student_model(
                    first_name=add_student_form.cleaned_data['first_name'],
                    last_name=add_student_form.cleaned_data['last_name'],
                    birthdate=add_student_form.cleaned_data['birthdate'],
                    grade=add_student_form.cleaned_data['grade'],
                    user=self.request.user
                )
                student.save()
                return self.form_valid(add_student_form)
            else:
                return self.form_invalid(add_student_form)

        if 'update_student' in request.POST:
            student_id = request.POST.get('student_id')
            student_instance = self.student_model.objects.get(id=student_id)
            edit_student_form = AddStudentForm(request.POST, instance=student_instance)
            if edit_student_form.is_valid():
                edit_student_form.save()
                return self.form_valid(edit_student_form)
            else:
                return self.form_invalid(edit_student_form)

        return super().post(request, *args, **kwargs)

base/templates/base_generic.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}Home School Logger{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    html,
    body {
      height: 100%;
    }

    body {
      display: flex;
      flex-direction: column;
    }

    main {
      flex: 1;
    }

    .footer {
      background: #f8f9fa;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  {% block extra_css %}{% endblock %}
  {% block extra_javascript %}{% endblock %}
</head>

<body class="d-flex flex-column min-vh-100">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
    <div class="nav-item dropdown">

      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </a>

      <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
        {%if request.user.is_authenticated%}
        <a class="dropdown-item" href="{% url 'base:home' %}">Home</a>
        <a class="dropdown-item" href="{% url 'base:profile' %}">Profile</a>
        <a class="dropdown-item" href="{% url 'logger:logs' %}">Student Logs</a>
        <a class="dropdown-item" href="{% url 'base:logout' %}">Logout</a>
        {%endif %}
      </div>
    </div>
    {% endif %}
    <a class="navbar-brand {% if not request.user.is_authenticated %}ps-3{% endif %}" href="{% url 'base:home' %}">Home School Logger</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse d-flex justify-content-end align-items-center" id="navbarNav">
      {% if user.is_authenticated and profile_info %}
      <p class="nav-item m-0 pe-3">
        Welcome, {{profile_info.first_name}} {{profile_info.last_name}}!
      </p>
      {% endif %}
    </div>
  </nav>

  <main class="container mt-5">
    {% block content %}{% endblock %}
  </main>

  <footer class="footer mt-auto py-3 text-center">
    <div class="container">
      <p>&copy; 2024 Home School Logger</p>
    </div>
  </footer>
</body>

</html>

base/templates/create_profile.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Teacher Profile</h2>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
              <button type="submit" class="btn btn-primary w-100">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

base/templates/home.html
{% extends "base_generic.html" %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5">Progress Dashboard</h1>
    
    <div class="row d-flex flex-row justify-content-center">
        {% for student, data in dashboard_data.items %}
        <div class="col-md-6 mb-4 text-center">
            <div class="card shadow-sm transition-all hover:shadow-lg">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">{{ student }}</h3>
                </div>
                <div class="card-body">
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" 
                             style="width: {% widthratio data.core_hours_at_home data.target_hours 100 %}%" 
                             aria-valuenow="{{ data.core_hours_at_home }}" 
                             aria-valuemin="0" aria-valuemax="{{ data.target_hours }}"></div>
                        <div class="progress-bar bg-info" role="progressbar" 
                             style="width: {% widthratio data.core_hours_away data.target_hours 100 %}%" 
                             aria-valuenow="{{ data.core_hours_away }}" 
                             aria-valuemin="0" aria-valuemax="{{ data.target_hours }}"></div>
                        <div class="progress-bar bg-warning" role="progressbar" 
                             style="width: {% widthratio data.elective_hours data.target_hours 100 %}%" 
                             aria-valuenow="{{ data.elective_hours }}" 
                             aria-valuemin="0" aria-valuemax="{{ data.target_hours }}"></div>
                    </div>
                    <div class="mt-3">
                        <div class="d-flex justify-content-between">
                            <span><i class="fas fa-square text-success"></i> Core Hours at Home</span>
                            <span>{{ data.core_hours_at_home }} hours</span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <span><i class="fas fa-square text-info"></i> Core Hours Away</span>
                            <span>{{ data.core_hours_away }} hours</span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <span><i class="fas fa-square text-warning"></i> Elective Hours</span>
                            <span>{{ data.elective_hours }} hours</span>
                        </div>
                    </div>
                    <div class="text-center mt-4 d-flex flex-row justify-content-around">
                        <div>
                            <h4>Total Hours: {{ data.total_hours }} / {{ data.target_hours }}</h4>
                            <p>Progress: {% widthratio data.total_hours data.target_hours 100 %}%</p>
                        </div>
                        <div>
                            <h4>Days Left: {{ data.days_left }}</h4>
                            <p>Average Hours to Complete: {{ data.average_hours_to_complete }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    

</div>
{% endblock %}

{% block extra_javascript %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // You can add some JavaScript here for additional interactivity if needed
</script>
{% endblock %}

base/templates/login.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Login</h2>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center">
              <button type="submit" class="btn btn-primary w-100">Login</button>
            </div>
          </form>
        </div>
        <div class="card-footer text-center">
          <p>Don't have an account?</p>
          <li class="list-unstyled btn btn-primary w-100"><a href="{% url 'base:signup' %}" class="text-white">Sign Up</a>
          </li>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

base/templates/profile.html
{% extends "base_generic.html" %}
{% load static crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Teacher</h2>
        </div>
        <div class="card-body">
          <h3>{{ profile_info.first_name }} {{ profile_info.last_name }}</h3>
          <h5>State: {{ profile_info.state }}</h5>
          <h5>Email: {{ profile_info.email }}</h5>
          <h5>User Name: {{ profile_info.user.username }}</h5>
          <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#profileModal">
            Edit Profile
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Students</h2>
        </div>
        <div class="card-body">
          {% for student in student_info %}
          <div class="card mb-1">
            <div class="card-body">
              <h3>{{ student.first_name }} {{ student.last_name }}
                <a class="fas fa-pencil-alt" href="#" data-bs-toggle="modal" data-bs-target="#editStudentModal"
                  data-student-id="{{ student.id }}" data-first-name="{{ student.first_name }}"
                  data-last-name="{{ student.last_name }}" data-birthdate="{{ student.birthdate|date:'Y-m-d' }}"
                  data-grade="{{ student.grade }}"></a>
              </h3>
              <h5>Birthdate: {{ student.birthdate|date:'M d, Y' }}</h5>
              <h5>Grade: {{ student.grade }}</h5>
            </div>
          </div>
          {% endfor %}

          <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#addStudentModal">
            Add Student
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Edit Student Modal -->
<div class="modal fade" id="editStudentModal" tabindex="-1" aria-labelledby="editStudentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editStudentModalLabel">Edit Student</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post">
          {% csrf_token %}
          {{ edit_student_form|crispy }}
          <input type="hidden" name="student_id" id="student_id">
          <button type="submit" name="update_student" class="btn btn-primary w-100">Save</button>
          <button type="button" class="btn btn-danger w-100 mt-2" data-bs-dismiss="modal">Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Edit Profile Modal -->
<div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="profileModalLabel">Edit Profile</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" name="edit_profile" class="btn btn-primary w-100">Save</button>
          <button type="button" class="btn btn-danger w-100 mt-2" data-bs-dismiss="modal">Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Add Student Modal -->
<div class="modal fade" id="addStudentModal" tabindex="-1" aria-labelledby="addStudentLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addStudentLabel">Add Student</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post">
          {% csrf_token %}
          {{ add_student_form|crispy }}
          <button type="submit" name="add_student" class="btn btn-primary w-100">Save</button>
          <button type="button" class="btn btn-danger w-100 mt-2" data-bs-dismiss="modal">Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extra_javascript %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
  });

  document.addEventListener('DOMContentLoaded', function () {
    // Prepopulate the profile modal
    var profileModal = document.getElementById('profileModal');
    profileModal.addEventListener('show.bs.modal', function (event) {
      var profileInfo = {
        first_name: "{{ profile_info.first_name }}",
        last_name: "{{ profile_info.last_name }}",
        state: "{{ profile_info.state.id }}",
        email: "{{ profile_info.email }}",
        username: "{{ profile_info.user.username }}"
      };

      // Prepopulate the form fields
      document.querySelector('[name="first_name"]').value = profileInfo.first_name;
      document.querySelector('[name="last_name"]').value = profileInfo.last_name;
      document.querySelector('[name="state"]').value = profileInfo.state;
      document.querySelector('[name="email"]').value = profileInfo.email;
      document.querySelector('[name="username"]').value = profileInfo.username;
    });

    // Prepopulate the edit student modal
    var editStudentModal = document.getElementById('editStudentModal');
    editStudentModal.addEventListener('show.bs.modal', function (event) {
      var button = event.relatedTarget; // Button that triggered the modal
      var studentId = button.getAttribute('data-student-id');
      var firstName = button.getAttribute('data-first-name');
      var lastName = button.getAttribute('data-last-name');
      var birthdate = button.getAttribute('data-birthdate');
      var grade = button.getAttribute('data-grade');

      // Prepopulate the form fields
      document.getElementById('student_id').value = studentId;
      document.querySelector('[name="first_name"]').value = firstName;
      document.querySelector('[name="last_name"]').value = lastName;
      document.querySelector('[name="birthdate"]').value = birthdate;
      document.querySelector('[name="grade"]').value = grade;
    });
  });
</script>
{% endblock %}

base/templates/signup.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h2>Sign Up</h2>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
              <button type="submit" class="btn btn-primary w-100">Sign Up</button>
            </div>
          </form>
        </div>
        <div class="card-footer text-center">
          <p>Already have an account?</p>
          <li class="list-unstyled btn btn-primary w-100"><a href="{% url 'base:login' %}" class="text-white">Log In</a>
          </li>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}